### ISSUE TITLE
State and shipping state mandatory fields

### ISSUE THREAD

**Issue by alkatsaros** [PAYONE-GmbH/woocommerce-3#16]
Hi,

I want to use PAYONE with woocommerce. I can see in the documentation of PAYONE API that orders from US, Canada, and some other countries have "state" and "shipping_state" as a mandatory credit card field.

Is it supported by this plugin? Many thanks!

**Comment by alkatsaros** [comment]
Hi @hreinberger,
thanks very much for your response. It would be great if you could fix it because without these fields it seems that people from those countries sometimes cannot pay with credit card.

**Comment by alkatsaros** [comment]
Hi @hreinberger,
is it may possible to advise me how I could temporarily solve the issue. If I added those 2 fields in the form and just copy with javascript the state and shipping_state from Woocommerce checkout form?

Thanks

**Comment by hreinberger** [comment]
Hi @alkatsaros 
this should work in most cases. Woocommerce sometimes sends state codes that differ from the way we're expecting them. This can lead to customers in China, Japan, Thailand or Mexico to get rejected due to unexpected state codes. 

So to make it right, one would have to translate the woocommerce state lists to the ones our API uses. We made the conscious decision to ignore this for the time being in favor of a quick solution. This solution is expected this week though, so if you can wait a couple more days you don't have to code it yourself.

**Comment by alkatsaros** [comment]
Hi @hreinberger,

what about this quick solution? It is a solution that will be applied to your plugin or to PAYONE API? Can we expect for this soon? If not maybe I will create an array with the countries where is mandatory to send state and shipping codes and map it with the ones that API uses.

Thanks for your responses and your help so far!

**Comment by hreinberger** [comment]
Fixed in 1.6.0 - not as quick a solution as planned :(
