### ISSUE TITLE
Send order number as reference instead of order ID

### ISSUE THREAD

**Issue by ahegyes** [PAYONE-GmbH/woocommerce-3#5]
Hello!

In the execute function in each gateway class there is the following line:

$this->set( 'reference', $order->get_id() );

A better choice would be to set the reference to $order->get_order_number(). This way, it would be compatible with WooCommerce Sequential Order Numbers Pro (https://woocommerce.com/products/sequential-order-numbers-pro/). If the plugin is not installed, get_order_number() just returns the same as get_id().

**Comment by hreinberger** [comment]
Hi @ahegyes 
thanks for the tip! We'll check that out.

**Comment by dolbertz** [comment]
Hej @ahegyes,

did you run into any specific compatibility issue with the order_id instead of order_number? We are currently discussing what this change would mean. Right now the order_id is used here to connect the Payone transaction with the WooCommerce order. It seems safer to just use the order_id, as the database itself makes sure, that is is unqiue. But we also see the problem, that a shop owner would have difficulties in finding his orders in the Payone backend.

Therefore it woul be great, if you had any further arguments.

**Comment by hreinberger** [comment]
Hi @ahegyes,
My biggest concern when using custom order numbers is the constraints our API has for the allowed characters in the reference.

I just pushed a new "develop" branch, where we use get_order_number() for the reference, but sanitize the reference according to our constraints. https://github.com/PAYONE-GmbH/woocommerce-3/tree/develop  This way, merchants can customize their order numbers and still won't get rejected due to forbidden characters. An order number like `#2018%12345` would get sent to us as `-2018-12345` which is still somewhat readable by a customer service agent. For full compatibility, the merchant would have to configure the custom order numbers according to the allowed characters from our API documentation (0-9, a-z, A-Z, .,-,_,/).

Since we don't have a licence for Sequential Order Numbers Pro we were only able to test if this new code doesn't break the existing behavior. Could you test this branch on a system with Sequential Order Numbers Pro so we can make sure it does what it's supposed to do?
