### ISSUE TITLE
Allow change of payment method

### ISSUE THREAD

**Issue by ahegyes** [PAYONE-GmbH/woocommerce-3#6]
Hello!

WooCommerce has a built-in functionality of allowing customers to change the payment method after a payment has been made (the form-pay.php template, the same one that is being used when a customer retries payment from their account on a failed order).

Currently, if the payment fails for Sofort/Credit Card/PayPal, the customer can re-attempt to pay using a different payment method, which is great. But for payment methods such as PrePayment, the plugin detects that the authorization was successful and when trying to pay using a different method (e.g., Sofort/PayPal), an error comes back saying that the reference has already been used.

Other BSPAYONE plugins, such as the one from customWeb, keep track of how many transactions have been attempted on an order and, for order P38 for example, send as reference P38 (first transaction), P38_1 (second transaction), P38_2 (third transaction) etc., which avoids the collision. This is very nice in allowing customers that opted for PrePayment, which takes approximately 3 days to register as paid, to change to PayPal and receive the payment confirmation within minutes (and thus have their order be processed much quickly). 

Thank you!

**Comment by hreinberger** [comment]
Hi @ahegyes 
this behavior makes sense for payment methods that redirect the customer to their sites (eg PayPal, sofort, Giropay). Because there can be technical difficulties during the redirect or the customer can decide to interrupt the payment. In this case the order is saved as pending payment and the customer can pay with another payment method and the same reference. Our platform then recognizes the incomplete payment and generates a new transaction with the new payment method, where the old reference is allowed.

However, when using payment methods that don't redirect the customer, the transaction is finalized immediately. Trying to change the payment method there would result in another transaction which needs its own reference. The first transaction can have more implications down the line, especially when using safe invoice, where unpaid invoices can lead to automatic dunning procedures.

So our implementation here plays it safe in allowing payment method switches only where there can be a legitimate issue with the first payment. If you want to change the payment method for prepayments, you would have to cancel the order and let the customer order again with another payment method. 

Nevertheless, I understand your wish to change payment methods on all orders from a convenience standpoint. I'll keep this in mind and if we find a clever solution to make changing payment methods easier for the customer and still doable on our API (without potential issues), we'll implement it further down the line.

**Comment by ahegyes** [comment]
Thanks for the reply! And yes, I understand the potentially undesired implications that payment methods like safe invoice can pose. 

Like you said, there are no issues and everything works as expected with payment methods like Sofort/PayPal/credit card which redirect to other portals and capture the payment straight away. 

There is however a way in WooCommerce to enable SafeInvoice and PrePayment to work nicely: the "Pay now" button only shows up (and the respective page can only be accessed) if the function is_paid() in the class WC_Order returns true. The return of the function can be filtered on the filter 'woocommerce_order_is_paid' which is normally only dependent on the order status (for example, by default the button is not available when the order is Processing, and since your plugin sets the order in Processing after capturing a payment, all is good). Since gateways that redirect get an immediate result as to whether the payment was captured or not (as far as I can tell from the plugin's code at least), they button always goes away right after a successful transaction. 

For SafeInvoice, there are no downsides whatsoever to the customer -- the order gets processed normally and they have to pay within 2 weeks through a bank transfer. Sofort/PayPal/Credit card also assume the existence of a bank account, so there everything is fine. In the context of this page, the filter can then always return true (as in the order is paid), and disable the ability to pay using a different payment method completely. There are 3 functions in WooCommerce which should help figure out the context properly:
is_account_page() -- checks that the customer is in their myaccount section
is_checkout() -- checks whether the customer is on the form-pay.php page OR in the regular checkout
is_checkout_pay_page() -- checks whether the customer is on the form-pay.php page

For PrePayment, as long as no payment was captured, all the plugin needs to do is keep track of how many transaction attempts there were an append the reference like _1, _2 etc. to subsequent transactions such that the API succeeds. We use this successfully using customWeb's BSPAYONE plugin on a few other projects and the Merchant Interface organizes everything nicely.

But these are just ideas off the top of my head right now so I might be missing something. I'll try to find some time to thinker with it properly and will let you know if I manage to find a way.

Thanks again for not dismissing the idea :)

**Comment by hreinberger** [comment]
OK so the only real case I would see where this would be useful (but doesn't work yet) is prepayment. In any other case where the order is still in pending payment this already works. I agree with you that this would be a convenient feature for users who want to switch payment methods after the fact. But right now this feels like too much of an edge case. We'll keep this feature on backlog and will see if this gains some traction in the future. Still thanks so much for your analysis and contribution though!
